"""Describe your change

Revision ID: 18c2fcfd2dc7
Revises: 868d62fb2917
Create Date: 2025-06-03 01:47:22.594837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c2fcfd2dc7'
down_revision: Union[str, None] = '868d62fb2917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
